# Generated by Django 5.0 on 2024-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp1', '0002_login_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
