# Generated by Django 5.0 on 2024-12-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp1', '0005_alter_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
