# Generated by Django 5.0 on 2025-01-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='posts/images/'),
        ),
    ]
