# Generated by Django 5.0 on 2024-12-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp1', '0006_alter_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
